### ISSUE TITLE
Add "Download as PNG, View Source, Edit on the online editor" to footer

### ISSUE THREAD

**Issue by gnestor** [altair-viz/jupyterlab_vega#24]
![screen shot 2017-02-25 at 9 46 10 pm](https://cloud.githubusercontent.com/assets/27600/23337476/d886b5fe-fba3-11e6-8649-85bb4065b1ac.png)

**Comment by gnestor** [comment]
@ellisonbg Was it ipyvega or jupyterlab_vega that provided these links? I can't find a reference to it.

from https://github.com/altair-viz/jupyterlab_vega/pull/17#issuecomment-282534936

**Comment by domoritz** [comment]
These links were provided by [vega-embed](https://github.com/vega/vega-embed).
