### ISSUE TITLE
Support for layered vega-lite?

### ISSUE THREAD

**Issue by rprimet** [altair-viz/jupyterlab_vega#38]
Hi,

Is there support for layered vega-lite plots (especially the kind that uses multiple `SingleViewSpec` instances, each one having its own data source)?

If not, is it planned?

Thanks!

**Comment by ellisonbg** [comment]
The current release of Altair, which is based on Vega-Lite 1.2 does have some basic layering. Here is a notebook showing how to use it:

https://github.com/altair-viz/altair_notebooks/blob/master/notebooks/07-LayeredCharts.ipynb

**Comment by rprimet** [comment]
Thanks. Does it also apply for the "straight" vega-lite module?

**Comment by kanitw** [comment]
Vega-lite 2.0 has layer support - See https://vega.github.io/vega-lite/docs/layer.html.
