### ISSUE TITLE
pip install jupyterlab_vega fails

### ISSUE THREAD

**Issue by bnmnetp** [altair-viz/jupyterlab_vega#40]
It looks like jupyterlab_vega is no longer available for pip to install. 

```
$ pip install jupyterlab_vega                      (jlab)
Collecting jupyterlab_vega
  Could not find a version that satisfies the requirement jupyterlab_vega (from versions: )
No matching distribution found for jupyterlab_vega
```

When I try to use altair in jupyter lab 0.31.5. I get the message

```
JavaScript output is disabled in JupyterLab
```

Can I use altair in the current version of jupyterlab?

**Comment by domoritz** [comment]
https://github.com/jupyterlab/jupyter-renderers supports Vega and we will soon move native support to Jupyter Lab. Altair will have to output mimetyped JSON.

**Comment by bnmnetp** [comment]
I figured it out, which is why I linked the PR to this issue so that others who find their way to this github project through Google will see that you no longer need the plugin and can just call ``enable_mime_rendering()``
